version: "2"

services:
  db:
    image: mdillon/postgis:9.4
    container_name: gps_collector_db
    environment:
      POSTGRES_DB: gps_collector
      POSTGRES_PASSWD: gps_collector
      POSTGRES_USER: gps_collector
    ports:
      - "5432:5432"
  app:
    image: app:latest
    container_name: app
    # Local only credentials.
    environment:
      POSTGRES_DB: gps_collector
      POSTGRES_PASSWD: gps_collector
      POSTGRES_USER: gps_collector
    build:
      context: ./docker
    volumes:
      # Live mount locally for immediate change inclusion.
      - ./docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./app:/app
      # Use docker volume for pip cache for faster rebuilds.
      - pip-cache:/root/.cache/pip
    ports:
      - "5000:5000"

volumes:
  pip-cache:
